version: 0.2

env:
  parameter-store:
    SSH_KEY: "EC2_SSH_KEY"

phases:
  pre_build:
    commands:
      - echo "Starting deployment..."
      - aws --version

  post_build:
    commands:
      - echo "Deploying to EC2..."
      - printf "%s\n" "$SSH_KEY" > private_key.pem
      - chmod 600 private_key.pem
      - ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@ec2-13-232-118-1.ap-south-1.compute.amazonaws.com "
          cd /home/ec2-user/aws-genai &&
          git pull &&
          docker stop aws-genai-server || true &&
          docker system prune -a -f --volumes &&
          docker-compose build --progress=plain &&
          docker-compose up -d"
